theme: jekyll-theme-minimal
title: FOSS4G Korea 2021
logo: https://foss4g.osgeo.kr/images/foss4gkorea-logo.png
description: OSGeo Korean Chapter
show_downloads: false
favicon: https://foss4g.osgeo.kr/images/favicon.ico
